language: objective-c
osx_image: xcode9
xcode_workspace: JSONValue.xcodeproj
xcode_scheme: JSONValue
xcode_sdk: iphonesimulator11.0
script:
 - set -o pipefail
 - xcodebuild -version
 - xcodebuild -showsdks
 - xcodebuild -project JSONValue.xcodeproj -scheme JSONValue -sdk iphonesimulator -destination "OS=11.0,name=iPhone 8" ONLY_ACTIVE_ARCH=NO build test
